config/routes.rb
Rails.application.routes.draw do

  resources :orders
  put 'fill_order/:id', to: 'orders#fill_order', as: 'fill_order'
  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations', passwords: 'passwords'}
  
  resources :line_items

  resources :carts
  
  
  root 'pages#index'

  get 'index' 	=> 'pages#index' 
  get 'tips'		=> 'pages#tips'
  get 'contact'	=> 'pages#contact'
  get 'about'		=> 'pages#about'
  get 'articles' => 'pages#articles'
  get 'videos'  => 'pages#videos'
  get 'welcome/index'	=> 'welcome#index'
  resources :products
  


end

app/models/product.rb
class Product < ActiveRecord::Base
	validates :productCode, presence: true
    has_many :line_items
    has_many :orders, through: :line_items
    belongs_to :productlines
    before_destroy :ensure_not_referenced_by_any_line_item
    
  def self.search(query)
   
    where("\"productName\" like ?", "%#{query}%") 
  end
   
 def change_stock(amount)
     if self.quantityInStock > amount
     self.quantityInStock = self.quantityInStock - amount
     
     else
       false
    end
   end 
     
    
    
    private 
        
        def ensure_not_referenced_by_any_line_item
            if line_items.empty?
                return true
            else errors.add(:base, 'Line Items present')
                return false
            end 
        end
    
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
 
    before_filter :assign_variable

	
    def index
        
       if params[:productLine]
        
		@products = Product.where("\"productLine\" = ?", params[:productLine])
        @title = "Showing category '#{params[:productLine]}'"
           
        elsif params[:search]
        @products = Product.search(params[:search])
        @title = "Your search for '#{params[:search]}' returned #{@products.count} result(s)"
        else
           @products = Product.all
           @title =  "Showing all products"
        end
        
	end

	def show
        
		@product = Product.find(params[:id])
	end

	def new
        authorize! :new, Product
		@product = Product.new
	end

	def edit
        authorize! :edit, Product
		@product = Product.find(params[:id])
        authorize! :edit, @product
	end

	def create
        authorize! :create, Product
		@product = Product.new(product_params)

		if @product.save
			redirect_to @product 
		else
			render 'new'
		end
	end

	def update
        authorize! :update, Product
		@product = Product.find(params[:id])

		if @product.update(product_params)
			redirect_to @product 
		else
			render 'edit'
		end
	end

	def destroy
        authorize! :destroy, Product
		@product = Product.find(params[:id])
		@product.destroy

		redirect_to products_path
	end
	private


	def assign_variable
   	@cart = current_cart
	end


	def product_params
		params.require(:product).permit(:productCode, :productName, 
			:productLine, :productScale, :productVendor, :productDescription, 
			:quantityInStock, :buyPrice, :MSRP)
	end
end

app/helpers/products_helper.rb
module ProductsHelper
    

end

app/views/products/_form.html.erb
<%= form_for @product do |f| %>

	<% if @product.errors.any? %>
		<div id="error_explanation">
			<h2>
				<%= pluralize(@product.errors.count, "error") %> prohibited 
					this product from being saved:
			</h2>
			<ul>
				<% @product.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<div class="container">
	<div class="col-sm-2">
	<p>
		<%= f.label :Product_Code %><br>
		<%= f.text_field :productCode %>
	</p>
	<p>
		<%= f.label :Product_Name %><br>
		<%= f.text_field :productName %>
	</p>
	<p>
		<%= f.label :productLine %><br>
		<%= f.text_field :productLine %>
	</p>
		<p>
		<%= f.label :productScale %><br>
		<%= f.text_field :productScale %>
	</p>
		<p>
		<%= f.label :productVendor %><br>
		<%= f.text_field :productVendor %>
	</p>
	</div>
	<div class="col-sm-2">
		<p>
		<%= f.label :productDescription %><br>
		<%= f.text_field :productDescription %>
	</p>
		<p>
		<%= f.label :quantityInStock %><br>
		<%= f.text_field :quantityInStock %>
	</p>
		<p>
		<%= f.label :buyPrice %><br>
		<%= f.text_field :buyPrice %>
	</p>
		<p>
		<%= f.label :MSRP %><br>
		<%= f.text_field :MSRP %>
	</p>
	<p>
		<%= f.submit %>
	</p>

	</div>
	</div>

<% end %>

app/views/products/edit.html.erb
<div class="container">
	<h1>Edit a Lugnuts Product</h1>
 	<div class="col-sm-4">
		<%= render 'form' %>

    <%= link_to 'Back to Product List', products_path %>
    </br><hr>
    <% if can? :create, @product %>
      <%= link_to "Admin: New Item", new_product_path %>
    <% end %>
    </br>
  </div>
</div>

app/views/products/index.html.erb
<div class= 'container'>
<% provide(:title, "Products") %>
    <div class='products'><h1><%=@title%></h1></div>
<div class='row'>
<table class='table'>
  <tr>
      <th>Product Name</th>
      <th>Quantity</th>
      <th>Price</th>
  </tr>
 
  <% @products.each do |product| %>
    
    <tr>
      
        <td><%= product.productName %></td>
        <td><%= product.quantityInStock %></td></div>
      <td><%= number_to_currency(product.MSRP) %></td>
     <td><%= link_to 'View', product_path(product), class: 'btn btn-primary'%></td>
         <td><%= button_to 'Add to Cart', line_items_path(product_id: product), class:'btn btn-primary', remote: true %></td>
    </tr>
  <% end %>
</table>
</div>



app/views/products/new.html.erb
<div class="container">
	<h1>Add a new Product to the Lugnuts database</h1>
 	<div class="col-sm-4">
		<%= render 'form' %>

    <%= link_to 'Back to Product List', products_path %>
    </br><hr>
    </br>
  </div>
</div>

app/views/products/show.html.erb
<div class="container">
  <h1> Lugnuts Product Item View</h1>
  <div class="col-sm-4">
    <p>
      <strong>Product Name:</strong>
      <%= @product.productName %>
    </p>

    <p>
      <strong>Product Line:</strong>
      <%= @product.productLine %>
    </p>

    <p>
      <strong>Product Description:</strong>
      <%= @product.productDescription %>
    </p>

    <p>
      <strong>Quantity in Stock:</strong>
      <%= @product.quantityInStock %>
    </p>

    <p>
      <strong>Price:</strong>
      <%= number_to_currency(@product.MSRP) %>
    </p>
    <%= button_to 'Add to Cart', line_items_path(product_id: @product.id), class:'btn btn-primary', remote: true %>
    </br>
    <%= link_to 'Back to Product List', products_path %>
    </br><hr>
    <% if can? :create, @product %>
      <%= link_to "Admin: New Item", new_product_path %>
    <% end %>
    </br>
    <% if can? :update, @product %>
      <%= link_to "Admin: Edit", edit_product_path(@product) %>
    <% end %>
    </br>
    <% if can? :destroy, @product %>
      <%= link_to "Admin: Destroy", product_path(@product), method: :delete, data: { confirm: "Are you sure you wish to delete this Product?" }  %>
    <% end %>


  </div>
</div>