config/routes.rb
Rails.application.routes.draw do

  resources :orders
  put 'fill_order/:id', to: 'orders#fill_order', as: 'fill_order'
  devise_for :users, :controllers => {sessions: 'sessions', registrations: 'registrations', passwords: 'passwords'}
  
  resources :line_items

  resources :carts
  
  
  root 'pages#index'

  get 'index' 	=> 'pages#index' 
  get 'tips'		=> 'pages#tips'
  get 'contact'	=> 'pages#contact'
  get 'about'		=> 'pages#about'
  get 'articles' => 'pages#articles'
  get 'videos'  => 'pages#videos'
  get 'welcome/index'	=> 'welcome#index'
  resources :products
  


end

app/views/layouts/_admin_buttons.html.erb
   <li class='dropdown btn btn-primary' id='admin-actions'>
            <a href='#' data-toggle='dropdown' class='dropdown-toggle', style='color:white'>Admin Actions</a>
            <ul class='dropdown-menu'  role='menu'>
                
                 <li style='display:block'><%= link_to 'View Orders',  orders_path %></li>
                <li><%= link_to "Add a Product", new_product_path %></li>
       </ul></li>

app/views/layouts/_footer.html.erb

<footer class="navf">
<hr>
<div>
  <small>
    Site design by Scripts and Tags 2015
  </small>
   </div>
    
</footer>


app/views/layouts/_header.html.erb

<div class='container'>
        <header class='<header class="navbar navbar-fixed-top navbar-inverse">'>
            
            <ul class='social'>
                <li><a href="http://facebook.com/"><i class="fa fa-facebook"></i></a></li>
        
                 <li><a href="http://twitter.com/"><i class="fa fa-twitter"></i></a></li>
                 <li><a href="http://plus.google.com/"><i class="fa fa-google-plus"></i> </a></li>
                <li><a href="http://tumblr.com"><i class="fa fa-tumblr"></i> </a></li>
                <li><a href="http://pinterest.com"><i class="fa fa-pinterest"></i> </a></li>
                <li><a href="http://youtube.com"><i class="fa fa-youtube"></i> </a></li>
            </ul>
            <ul>
             
                <% if user_signed_in? %>
                <li>Logged in as <strong><%= current_user.email %></strong></li>
                <li><%= link_to 'Edit profile', edit_user_registration_path, :class => 'btn btn-primary' %></li>
                <li><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'btn btn-primary'  %></li>
                <% else %>
                <li><%= link_to "Sign up", new_user_registration_path, :class => 'btn btn-primary'  %></li>
                    
                <li><%= link_to "Login", new_user_session_path, :class => 'btn btn-primary', :id =>'login'  %>
                <div id='login-content'><%= render 'layouts/login'%> </div>
                
                </li>
                
                <% end %>
            
      <% unless controller.controller_name == 'orders' || user_signed_in? && current_user.admin == true %>  <li><%=link_to "Cart (#{item_count(@cart)})" , @cart, id:'cart', class:'btn btn-primary'%>
               
   
                <div id='cart_view'><%= render @cart %></div> 
                </li><%end%>
            
           <%if user_signed_in? && current_user.admin == true %> <%=render 'layouts/admin_buttons'%><%end%></ul>
            
    </header>
</div>
	<div class='container-fluid'><div class='row' id='logo'>
            <div class='col-md-12'>
                <%= link_to image_tag("logo.jpg", alt: "Lugnuts Auto Parts logo"), root_path %>
                <% if flash[:notice] %>
    <div class="notice"><%= flash[:notice] %></div>
  <% end %>
        </div>
        </div>
</div>
<%= render 'layouts/header_navbar' %>
  

app/views/layouts/_header_navbar.html.erb
<div class='container-fluid'>
 <nav class='nav nav-bar-default'>
   <ul class="navb">
        <li><%= link_to "Home",     root_path %></li>
           <li class='dropdown'>
            <a href='#' data-toggle='dropdown' class='dropdown-toggle'>Products</a>
            <ul class='dropdown-menu' role='menu'>
                 <% Productline.all.each do |p| %>
                 <li><%= link_to p.productLine, products_path(:productLine => p.productLine) %></li>
                 <% end %>
                <li><%= link_to "All Products", products_path %></li>
            </ul>
            
            </li>
         <li class='dropdown'>
            <a href='#' data-toggle='dropdown' class='dropdown-toggle'>Tips</a>
            <ul class='dropdown-menu' role='menu'>              
                 <li><%= link_to "Articles", articles_path %></li>                
                 <li><%= link_to "Instructional Videos", videos_path %></li>
            </ul>
            
            </li>
        <li><%= link_to "Contact",  contact_path %></li>
        <li><%= link_to "About",    about_path %></li>
    </ul>
      <%=form_tag(products_path, :method=>"get",  role: 'search', class: 'navbar-form navbar-right') do %>
        <div class='form-group'>
            <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search products..." %>
            <input type='submit' name='searchbtn' id='searchbtn' class='btn btn-primary'></div><%end%>
      </form>
    </nav>
</div>

app/views/layouts/_login.html.erb
<h2>Log in</h2>

<p style='color:red' id='login-fail'></p>
<%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <% if devise_mapping.rememberable? -%>
    <div class="field">
      <%= f.check_box :remember_me %>
      <%= f.label :remember_me %>
    </div>
  <% end -%>

  <div class="actions">
    <%= f.submit "Log in" %>
  </div>
<% end %>

<%= render "devise/shared/links" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
 		<title><%= full_title(yield(:title)) %></title>
        
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
 		<%= csrf_meta_tags %>
        
 </head>
	<body>
    <div id= 'wrapper'>
       <div id='header'>
		   <%= render 'layouts/header' %>
       </div>
        <div id='body'>
		    <%= yield %>
        </div>
		<div id='footer'>
          <%= render 'layouts/footer' %>
        </div>
        </div>
	</body>
</html>